version: '3.8'

services:
  # NGINX Load Balancer
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Mount custom config
    depends_on:
      - app
    networks:
      - zap-url-network

  # Spring Boot App (Scalable)
  app:
    image: zap-url-app
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/zap_url
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      SERVER_PORT: 8080  # All instances use the same port (Docker handles routing)
    networks:
      - zap-url-network

  # PostgreSQL & Redis (unchanged)
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: zap_url
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - zap-url-network

  redis:
    image: redis:latest
    command: ["redis-server", "--bind", "0.0.0.0"]
    volumes:
      - redis_data:/data
    networks:
      - zap-url-network

networks:
  zap-url-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data: