server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://db:5432/zap_url
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  redis:
    host: redis
    port: 6379
    timeout: 5000
    connect-timeout: 10000
    retry:
      max-attempts: 5
      initial-interval: 1000
      max-interval: 5000
      multiplier: 2

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG