spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/shorturl
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  spring:
    redis:
      host: redis
      port: 6379

logging:
  level:
    root: INFO